name: rakaat_tracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.0+21

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  proximity_sensor: ^1.0.4
  flutter_sensors: ^1.0.1
  flutter_neumorphic: ^3.2.0
  flutter_qiblah: ^2.1.0
  google_fonts: ^3.0.1
  flutter_svg: any
  delayed_display: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  bottom_bar_page_transition: ^2.0.0
  concentric_transition: ^1.0.3
  change_app_package_name: ^1.1.0
  geolocator: ^9.0.2
  responsive_sizer: ^3.1.1
  flutter_vibrate: ^1.3.0
  light_sensor: ^2.0.2
  flutter_tts: ^3.6.3
  fluttertoast: ^8.2.2
  type_text: ^1.0.5
  animation_wrappers: ^3.0.0
  facebook_audience_network: ^1.0.1
  applovin_max: ^3.0.1
  firebase_core: ^2.14.0
  firebase_remote_config: ^4.2.3
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.11
  advanced_in_app_review: ^1.1.3
  wakelock_plus: ^1.1.1
  in_app_purchase: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/
